"""initial empty migration

Revision ID: ac7606d9182e
Revises:
Create Date: 2026-07-19 23:18:16.519148

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ac7606d9182e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
