"""Constants shared across authentication components."""

AUTH_TAG = "Authentication"

ACCESS_TOKEN_COOKIE_NAME = "adaptive_access_token"
REFRESH_TOKEN_COOKIE_NAME = "adaptive_refresh_token"

ROLE_STUDENT = "student"
ROLE_INSTRUCTOR = "instructor"
ROLE_REVIEWER = "reviewer"
ROLE_ADMIN = "admin"

SUPPORTED_ROLES = (
    ROLE_STUDENT,
    ROLE_INSTRUCTOR,
    ROLE_REVIEWER,
    ROLE_ADMIN,
)

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128

OTP_LENGTH = 6
OTP_MAX_ATTEMPTS = 5
OTP_RESEND_COOLDOWN_SECONDS = 60

MAGIC_LINK_TOKEN_BYTES = 32
MAGIC_LINK_RESEND_COOLDOWN_SECONDS = 60
