"""Constants shared across authentication components."""

AUTH_TAG = "Authentication"

ACCESS_TOKEN_COOKIE_NAME = "adaptive_access_token"
REFRESH_TOKEN_COOKIE_NAME = "adaptive_refresh_token"

OAUTH_PROVIDER_GOOGLE = "google"
OAUTH_PROVIDER_GITHUB = "github"

ROLE_STUDENT = "student"
ROLE_PROFESSIONAL = "professional"
ROLE_ADMIN = "admin"

SUPPORTED_ROLES = (
    ROLE_STUDENT,
    ROLE_PROFESSIONAL,
    ROLE_ADMIN,
)

PERMISSION_PROFILE_READ = "profile:read"
PERMISSION_ASSESSMENTS_TAKE = "assessments:take"
PERMISSION_ASSESSMENTS_CREATE = "assessments:create"
PERMISSION_USERS_READ = "users:read"
PERMISSION_USERS_MANAGE = "users:manage"

ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    ROLE_STUDENT: frozenset(
        {
            PERMISSION_PROFILE_READ,
            PERMISSION_ASSESSMENTS_TAKE,
        }
    ),
    ROLE_PROFESSIONAL: frozenset(
        {
            PERMISSION_PROFILE_READ,
            PERMISSION_ASSESSMENTS_TAKE,
            PERMISSION_ASSESSMENTS_CREATE,
        }
    ),
    ROLE_ADMIN: frozenset(
        {
            PERMISSION_PROFILE_READ,
            PERMISSION_ASSESSMENTS_TAKE,
            PERMISSION_ASSESSMENTS_CREATE,
            PERMISSION_USERS_READ,
            PERMISSION_USERS_MANAGE,
        }
    ),
}

SUPPORTED_OAUTH_PROVIDERS = (
    OAUTH_PROVIDER_GOOGLE,
    OAUTH_PROVIDER_GITHUB,
)

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128

OTP_LENGTH = 6
OTP_MAX_ATTEMPTS = 5
OTP_RESEND_COOLDOWN_SECONDS = 60

MAGIC_LINK_TOKEN_BYTES = 32
MAGIC_LINK_RESEND_COOLDOWN_SECONDS = 60
